### ISSUE TITLE
PAAD not importing

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/cBioPortalData#1]
http://www.cbioportal.org/study?id=paad_tcga

**Comment by asamedy** [comment]
Error in .generateMap(colData, experiments) : 
  no way to map colData to ExperimentList

**Comment by asamedy** [comment]
http://www.cbioportal.org/study?id=luad_tcga
In .generateMap(colData, experiments) : Data from rows:
 NA - TCGA-55-7724-01
 NA - TCGA-55-7726-01 dropped
