### ISSUE TITLE
Travis build not working

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/cBioPortalData#14]
```
> downloadStudy("laml_tcga_pub", use_cache = tempdir())
Error in downloadStudy("laml_tcga_pub", use_cache = tempdir()) : 
  could not find function "downloadStudy"
Execution halted
```

But Appveyor is working, why is that?

**Comment by LiNk-NY** [comment]
Hi Levi, @lwaldron 
That was an issue in the documentation where I had examples for an internal function. 
https://github.com/waldronlab/cBioPortalData/commit/d59719a30585ac6eead51439566cbccbbc83086d#diff-01c00eede9af93ee1953ea021f0497beL23-L27

I fixed it by removing it in latest version of the package.
Internal functions shouldn't really have examples as they are not exported. 

The current Travis issue I'm having is the auto-stop when there is no output in the Travis console: 
https://travis-ci.org/github/waldronlab/cBioPortalData
This happens during the vignette build. 

Best,
Marcel
