### ISSUE TITLE
Error: Provide a valid 'studyId' from 'getStudies()'

### ISSUE THREAD

**Issue by jcgu** [waldronlab/cBioPortalData#19]
hi there,

I started using this tool recently and run into this error when checking on the simple example provided. 

```
cbio <- cBioPortal()
clinicalData(cbio, "acc_tcga")

```
```
Error in clinicalData(cbio, "acc_tcga") : 
  Provide a valid 'studyId' from 'getStudies()'
```

I looked into the code and understood the logic of `.checkIdValidity` but I couldn't figure out why it gave a `FALSE` for "acc_tcga". 

I've tried the version on bioC and also the version here on GitHub and have the same issue. 

Could you look into this?

Thanks.

**Comment by LiNk-NY** [comment]
Hi @jcgu, 
This has been resolved. See #15.
Please get the newest version of cBioPortalData either on GitHub `2.1.0` or Bioconductor. 
Best,
Marcel

**Comment by jcgu** [comment]
thanks, it's working with the latest on GitHub.
