### ISSUE TITLE
Add CI test for manuscript

### ISSUE THREAD

**Issue by inodb** [waldronlab/cBioPortalData#20]
- [ ] Figure S2B (skipping cBioDataPack for now since that's very slow: https://github.com/cBioPortal/datahub/issues/1166)
- [ ] Other figures: S2A, S2C + S3
- [ ] Main figures (different repo, might be able to reuse)

We can run the CI test on cbioportal/cbioportal using GitHub actions. It will pull a Rmd file with all the figures/supplementary code from somewhere (maybe this repo waldronlab/cBioPortalData?) and make sure it can finish within reasonable time

**Comment by LiNk-NY** [comment]
@inodb 
This is the repository that contains the rest of the analyses in the manuscript:
https://github.com/LiNk-NY/curatedTCGAManu
The only `cBioPortalData` code is in the `README.md` file.

**Comment by inodb** [comment]
@LiNk-NY thanks, that's great! Looks like I can pull the https://github.com/LiNk-NY/curatedTCGAManu/blob/master/README.Rmd file and run that 👍

**Comment by LiNk-NY** [comment]
BTW @inodb I've added the Bioc long tests option to this repository.
It allows tests in the `longtests` directory to run for up to 6 hours. 
If you'd like to add some unit tests there, you could.
