### ISSUE TITLE
Importing without a gene panel?

### ISSUE THREAD

**Issue by jucor** [waldronlab/cBioPortalData#24]
Hi!
Is there a way to import a study without having to specify a gene panel, please? For example:
```r
cBioPortalData(api = cbio,  studyId = "coadread_genentech")
```
which right now fails because I did not specify a gene panel. The web interface does not seem to require it either, nor does `cBioDataPack()`.
Thanks for any help!

**Comment by LiNk-NY** [comment]
Hi Julien, @jucor 
Thank you for your issue.
The cBioPortal API requires a set of genes in every query.
The easiest way to implement this was using existing gene panels.

Future versions will support a set of genes as input to the `cBioPortalData` function. 
I will leave this issue open until that is added. Thank you. 
Best,
Marcel

**Comment by jucor** [comment]
Thanks @LiNk-NY ! Any idea how to get the whole-genome sequence for studies that support it, by any chance, please? Or is the only way to download the whole database of studies and do queries on a local mirror?

**Comment by LiNk-NY** [comment]
@jucor You can download the entire study file using `downloadStudy`. It currently is an internal function but it can certainly be exported. 
```
cBioPortalData:::downloadStudy("coadread_genentech")
```

**Comment by LiNk-NY** [comment]
**update**: I've made `downloadStudy` available via the interface for use. 

@jucor Can you elaborate on what you mean by obtaining the whole-genome sequence for studies? 
Do you mean all the features (genes, CpGs, etc.) in a particular study?

Perhaps @inodb can provide additional information about this.  

Thanks

**Comment by LiNk-NY** [comment]
Hi Julien, @jucor 
As of version `2.3.5`, you should be able to provide a set of genes (either "entrezGeneId" or "hugoGeneSymbols") to the main function. See the diff of changes here: https://github.com/waldronlab/cBioPortalData/compare/9e394190ecd06495683934f965a4a76fd598c18d..master

**Comment by vemuribv** [comment]
Hello,
Just wanted to piggyback on this if possible--it seems the `downloadStudy` option mimics `cBioDataPack` functionality (unless I'm missing something). I'm wondering if I can use `cBioPortalData` to grab all the genes in one particular molecular profile, rather than a specified subset.

For example, I know that 'kirc_tcga' has a RNA_Seq_v2_expression_median experiment available with 20,531 rows (genes) and 534 columns (samples). To access just that experiment, rather than the whole study, I was hoping to do something like this:
```
cBioPortalData(api = cbio, by = "entrezGeneId", studyId = 'kirc_tcga', molecularProfileIds = c('kirc_tcga_rna_seq_v2_mrna'))
```
to get all 20,531 genes without specifying a subset. As you'd expect, this currently gives the following error:
```
Error in molecularData(api = api, molecularProfileIds = molecularProfileIds,  : 
  Provide a character vector of 'entrezGeneIds'
```
Right now I'm using `cBioDataPack` to download the full study and get to the RNA data that way, which is working fine and isn't too much of a hassle. But if I could use `cBioPortalData` to download just that specific molecular profile it would be super helpful mostly in terms of download time and a more streamlined workflow. Just wanted to see if that's doable with this function. 

Thank you!

**Comment by LiNk-NY** [comment]
Hi @vemuribv 

> it seems the `downloadStudy` option mimics `cBioDataPack` 

Yes, this is what is used internally along with a couple of other functions 

Unfortunately, the API is not designed to provide all the genes in a particular study by default.
It requires a list of genes or a gene panel for more granular access to the data. If you're interested
in _all_ the genes in a molecular profile, your best bet is `cBioDataPack`.

**Comment by jucor** [comment]
Chiming back super late. What worked for me (TM) in the end has been just
downloading the TSV directly from the Data Hub in R with curl, and
wrangling that, since my use cases were pretty targeted and really needed
the whole profile. I put some caching on top to avoid redownloading
everything every time. Not ideal, but good enough for what I needed :/

**Comment by LiNk-NY** [comment]
Thanks Julien, @jucor 

I wonder how your method is different from `cBioDataPack`, in terms of the data downloaded.
It would be interesting to compare. 

```r
> cBioDataPack("coadread_genentech")
Study file in cache: coadread_genentech
Working on: /tmp/RtmpD3Wve3/684b1aec006c_coadread_genentech/coadread_genentech/data_mutations_extended.txt
Working on: /tmp/RtmpD3Wve3/684b1aec006c_coadread_genentech/coadread_genentech/data_mutations_mskcc.txt
harmonizing input:
  removing 2 colData rownames not in sampleMap 'primary'
A MultiAssayExperiment object of 2 listed
 experiments with user-defined names and respective classes.
 Containing an ExperimentList class object of length 2:
 [1] mutations_extended: RaggedExperiment with 36271 rows and 72 columns
 [2] mutations_mskcc: RaggedExperiment with 36271 rows and 72 columns
Functionality:
 experiments() - obtain the ExperimentList instance
 colData() - the primary/phenotype DataFrame
 sampleMap() - the sample coordination DataFrame
 `$`, `[`, `[[` - extract colData columns, subset, or experiment
 *Format() - convert into a long or wide DataFrame
 assays() - convert ExperimentList to a SimpleList of matrices
 exportClass() - save all data to files
```

**Comment by jucor** [comment]
Apologies for delay answering - down with covid.
My method is much more barebones: I just download the TSV for mutations_mskcc_extended, and read it into a tibble. This also allowed me to configure the parsing of the TSV with readr to eliminate erroneous field type inference - which led to samples being dropped. I lose the rich MultiAssayExperiment structure,nl but I also simplify my code by only handling a single tibble - or two, when I include CNA.
