### ISSUE TITLE
geneTable()

### ISSUE THREAD

**Issue by xinwei-sher** [waldronlab/cBioPortalData#29]
geneTable() returns exactly 100,000 genes. Is that all?
Why most of the genes from geneTable() are phosphoprotein, and there are only 3477 protein-coding genes?
> geneTable(cbio) %>% group_by(type) %>% summarise(n=n())

# A tibble: 9 x 2
  type               n
  <chr>          <int>
1 miRNA           3925
2 ncRNA              6
3 other            158
4 phosphoprotein 91907
5 protein-coding  3477
6 pseudo           291
7 rRNA               2
8 tRNA              22
9 unknown          212

Such as, 
95817 | CCDC61_PT285 | phosphoprotein | NA | NA | NA
-- | -- | -- | -- | -- | --
20 | -95816 | CCDC61_PS447 | phosphoprotein | NA | NA | NA
21 | -95815 | FCGBP_PY614 | phosphoprotein | NA | NA | NA
22 | -95814 | FCGBP_PT624 | phosphoprotein | NA | NA | NA

Even TP53 is not there:
> geneTable(cbio) %>% filter(hugoGeneSymbol=="TP53")
# A tibble: 0 x 6
# ... with 6 variables: entrezGeneId <int>, hugoGeneSymbol <chr>, type <chr>, cytoband <chr>, length <int>, chromosome <chr>
Warning message:
`...` is not empty.

How come?

**Comment by LiNk-NY** [comment]
@xinwei-sher 
Thanks for reporting the issue. 
I am preparing a patch. There are pagination parameters in the API that are not explicit in the function arguments.
