### ISSUE TITLE
clinicalData does not retrieve all patient data

### ISSUE THREAD

**Issue by afaissa** [waldronlab/cBioPortalData#42]
Hi, thanks for the package!

A question, though:

Using the command:
PatientData <- clinicalData(api = cbio, studyId = "luad_tcga")

I get only 24 columns from patient metadata (no survival data, for example). Conversely, downloaded data from "luad_tcga" (data_bcr_clinical_data_patient.txt) gives 79 columns. So, I am not getting all the patient data using that command.

What am I doing wrong?

Tks.

**Comment by LiNk-NY** [comment]
Hi @afaissa 

When reporting issues like these it's best to provide at least the `sessionInfo` output. 
A minimally reproducible example is ideal. 

I checked release and devel versions of `cBioPortalData` and I get 81 columns. 

Please make sure you are using the latest Bioconductor release version 3.13 or
Bioconductor devel with R version 4.1 and that `BiocManager::valid()` returns `TRUE`/ 

https://bioconductor.org/packages/devel/bioc/html/cBioPortalData.html

Best regards,
Marcel

**Comment by LiNk-NY** [comment]
Feel free to re-open if the issue persists. Thanks!

**Comment by afaissa** [comment]
Hi Marcel, 

Thank you for your feedback and sorry for the missing information. 

library(cBioPortalData)
cbio <- cBioPortal()
PatientData <- clinicalData(api = cbio, studyId = "luad_tcga")

sessionInfo()
