### ISSUE TITLE
Require R>4.2.0?

### ISSUE THREAD

**Issue by Jeff-Gui** [waldronlab/cBioPortalData#46]
When installing as described in this github homepage, there is an error message.
ERROR: this R is version 4.1.2, package 'cBioPortalData' requires R >=  4.2.0

However, I think R has not been updated to 4.2.0 yet.

**Comment by lwaldron** [comment]
Hi @Jeff-Gui , the version on GitHub must be run with bioc-devel (https://www.bioconductor.org/developers/how-to/useDevel/), which depends on R-devel, which is currently 4.2.0. To use the release version of cBioPortalData that installs with the current Bioconductor and R releases, just do:
```r
BiocManager::install("cBioPortalData")
```
I'll clarify this on the README.md.
