### ISSUE TITLE
compatibility with paediatric cBio?

### ISSUE THREAD

**Issue by andrea-de-micheli** [waldronlab/cBioPortalData#49]
Hello,

I'm trying to access the data on the paediatric cBioPortal (https://pedcbioportal.kidsfirstdrc.org) using the following API address: https://pedcbioportal.kidsfirstdrc.org/api/swagger-ui.html

While I can create a cBioPortal instance, methods such as getStudies() and clinicalData() return me errors. 

Is the code compatible with the paediatric cBioPortal database?

Many thanks,
Andrea

**Comment by LiNk-NY** [comment]
Hi Andrea, @andrea-de-micheli
Please see the answer here: https://groups.google.com/g/cbioportal/c/VteZnY5C6mM/m/0GatSYyuAwAJ
Make sure you have version `2.7.7` of `cBioPortalData`.
Best,
Marcel

**Comment by andrea-de-micheli** [comment]
Thank you very much!

**Comment by LiNk-NY** [comment]
Please feel free to reopen, if there are still any difficulties. 
Thanks!
