### ISSUE TITLE
Can we make the download URL customizable?

### ISSUE THREAD

**Issue by SRodenburg** [waldronlab/cBioPortalData#59]
Hello,

Currently the package is preconfigured to download from the cBio Amazon server:
https://github.com/waldronlab/cBioPortalData/blob/b16ec9de5841a132cda1bc792a52dd7f44f3cbaa/R/cBioDataPack.R#L2

Would it be possible to make this URL customizable?

Thanks

**Comment by LiNk-NY** [comment]
Hi @SRodenburg 

Sorry I missed the issue notification. 
I hope you were able to change the URL. 
Please tag me next time. 

Best regards,
Marcel

**Comment by SRodenburg** [comment]
Thanks for the reply. I noticed that you should be able to change the URL using `option()`.
I missed that. Thanks!
