### ISSUE TITLE
Possible mistake in .isNonExp function causes files (CNA etc) to be loaded as metadata?

### ISSUE THREAD

**Issue by SRodenburg** [waldronlab/cBioPortalData#63]
Hello,

I was loading a study using the function `loadStudy` and noticed that most data files are not being added to the `ExperimentList` of the `MultiAssayExperiment` object, but are loaded as metadata into the MultiAssayExperiment object.

I pinpointed the issue to be in this line:
https://github.com/waldronlab/cBioPortalData/blob/devel/R/cBioDataPack.R#L426

it causes all non-mutation files to be dropped after loading. The difference is that mutation files are `RaggedExperiment` objects and e.g. the CNA are `DataFrame` objects...

Is this behaviour intentional?

Thanks

**Comment by SRodenburg** [comment]
If I am misunderstanding the code, please explain what the intended behavior is of this line/function.

**Comment by LiNk-NY** [comment]
Hi @SRodenburg 
Do you have a reproducible example? 
It may be that they do not have the proper annotations to be added into the `MultiAssayExperiment`.
Best,
Marcel

**Comment by SRodenburg** [comment]
Hello @LiNk-NY,
I am working with a custom dataset, and therefore I had to use the `loadStudy` method rather than the `cBioPortalPack` method.  The dataset is however cBioPortal compatible so I don't understand which annotations might be missing. Do you have some pointers to what I might check?

I saw the code does some checks on whether the dataset is TCGA or not. Might that be the issue?

Since it's a private dataset I do not have an example readily available. I will try to recreate the issue with a public study.

Thanks

Sander

**Comment by LiNk-NY** [comment]
Hi Sander, @SRodenburg 

> I saw the code does some checks on whether the dataset is TCGA or not. Might that be the issue?

Yes, that might be the issue since there is no easy way (in non-TCGA data) to link patient data to sample data for the `sampleMap`. But, you can still manually add the data in the metadata to the experiments. 

Best,
Marcel
