### ISSUE TITLE
Does the API provide download of variants?

### ISSUE THREAD

**Issue by zhongguojie1998** [waldronlab/cBioPortalData#66]
Hi cBioPortalData authors, thanks for developing such useful tool. May I ask if the cBioPortalData package provide API access to download data of variants on all patients of a gene, just like what we could do with the "Quick Search" on web portal? Sorry if I missed anything but it seems not clear on the API documentation. I'd really appreciate it if someone could help me with that, thank you!

**Comment by LiNk-NY** [comment]
Hi @zhongguojie1998 
I do not know if there is an endpoint for this. It may just be a feature of the website. 
You will have to ask https://github.com/cbioportal/cbioportal
