### ISSUE TITLE
Error using cBioportalData on Genie data

### ISSUE THREAD

**Issue by ZWael** [waldronlab/cBioPortalData#70]
Hello CbioPortalData  Team,

I was using the R package cBioPortalData as recommended here by genie.cbioportal.org
https://docs.cbioportal.org/web-api-and-clients/#r-client
but having some errors
here is my code 
```
cbio=cBioPortal(
    hostname = "genie.cbioportal.org",
    token = "xxxxx" # extracted from the https://genie.cbioportal.org/webAPI#using-data-access-tokens (download button)
)

Error in cBioPortal(hostname = "genie.cbioportal.org", token = "xx") : 
unused argument (token = "xx")
```
1) Does the cBioPortal function support a token argument ?

I commented the token argument
but I had an other error when extracting studies
```
getStudies(cbio)
Error in x[["pmid"]] : object of type 'externalptr' is not subsettable
```
2) Does cBioPortalData works on genie.cbioportal.org

**Comment by LiNk-NY** [comment]
Hi @ZWael 
Thank you for submitting the issue. I've added a helper function to parse tokens from the genie service. 
You can try and see the updated version 2.13.6 
It should work with the data at genie.cbioportal.org. 
If not open a new issue specific to the data

**Comment by ZWael** [comment]
@LiNk-NY  Nice work, could you have a friendly update with R 4.1.1 ?

**Comment by LiNk-NY** [comment]
@ZWael Bioconductor versions are tied to R versions so unfortunately, I don't have one. If possible, update your R version. Otherwise, you could try to install from GitHub but it is not guaranteed to work.

**Comment by ZWael** [comment]
@LiNk-NY, I will try a a work around or updating my R version.
Thank you for this nice package.
