### ISSUE TITLE
API changes?

### ISSUE THREAD

**Issue by denoqo** [waldronlab/cBioPortalData#75]
Hello,

It seems the cBioPortal() keeps failing to connect to cBioportal. 
Wondering if it is just a temporary thing?

```
> cbio <- cBioPortal()
Error: '.service_validate_md5sum' failed:
  Not Found (HTTP 404).
```

Thank you for your help!

[Package cBioPortalData version 2.8.1
[R 4.2.0]

**Comment by denoqo** [comment]
Ok, I think cbiportal changed their API.

Below worked for me:
```
cbio = cBioPortalData::cBioPortal(
  hostname = "www.cbioportal.org",
  protocol = "https",
  api. = "/v3/api-docs/public",  # update here
  token = character()
)
```
Ref: https://www.cbioportal.org/swagger-ui/index.html?urls.primaryName=public

**Comment by LiNk-NY** [comment]
Hi @denoqo 
Thank you for reporting. I will take a look.

**Comment by LiNk-NY** [comment]
cBioPortal has changed to new V3 API. It will take a bit longer to update `cBioPortalData` to the new API. Apologies for the delay.

**Comment by LiNk-NY** [comment]
**Update**: The cBioPortal team has decided to keep the V2 API at the same location and publish the V3 API at a new URL. This will allow all tools using the old URL to keep working. That means it will keep working as before so you should no longer see the errors. Thanks!

**Comment by denoqo** [comment]
Thank you so much!
